# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spree_solr_search}
  s.version = "0.40.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Roman Smirnov}]
  s.date = %q{2011-08-11}
  s.description = %q{Provides search via Apache Solr for a Spree store.}
  s.email = %q{roman@railsdog.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  
  s.files = `git ls-files`.split("\n")
  s.homepage = %q{http://github.com/romul/spree-solr-search}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{Provides search via Apache Solr for a Spree store.}

  s.add_dependency('spree_core', '>= 0.70.0')
  s.add_dependency('acts_as_solr_reloaded', '>= 1.6.0')
end

